packages:
  setuptools:
    exclude_patterns:
      - pattern: '**/_distutils_hack/**'
      - pattern: '**/distutils-precedence.pth'
      - pattern: '**/setuptools/**'
      - pattern: '**/pkg_resources/_vendor/**'
  zlib:
    exclude_patterns:
      - pattern: '**/so'
  widgetsnbextension:
    exclude_patterns:
      - pattern: '**'
  numpy:
    exclude_patterns:
    - pattern: '**/*.pyx'
    - pattern: '**/*.pyc'
    - pattern: '**/*.typed'
    - pattern: '**/*.egg-info'
default:
  exclude_patterns:
    - pattern: 'bin/**'
    - pattern: '**/bin/**'
    - pattern: 'tests/**'
    - pattern: '**/tests/**'
    - pattern: '**/*.ini'
    - pattern: '**/*.exe'
    - pattern: '**/*.c'
    - pattern: '**/*.pxd'
    - pattern: '**/*.pyi'
    - pattern: '**/*.pyx'
    - pattern: '**/*.pyc'
    - pattern: '**/*.typed'
    - pattern: '**/*.egg-info'
    - pattern: '**/site-packages/pip/_vendor/**'
    - pattern: '**/idlelib/**'
    - pattern: '**/ensurepip/**'
    - pattern: 'Scripts/*'
